# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Premier Platform for Online Trading | Binary.com
pr_title: Get Paid for Pull Requests | Binary.com
description: > # this means to ignore newlines until "baseurl:"
  Sign up for a risk-free virtual account and start trading with instant access to $10,000 in virtual funds.
pr_description: > # this means to ignore newlines until "baseurl:"
  To encourage transparency and improve the performance and functionality of our website, Binary.com has open-sourced the entire front-end of our codebase, and we are now actively encouraging the community to contribute to its development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zakibinary.github.io/amp-landing-pages" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
  - node_modules
  - assets/sass
  - assets/css
